general {
    lock_cmd = pidof hyprlock || hyprlock
    ceck_color = rgba(0, 0, 0, 0)
    before_sleep_cmd = playerctl pause ; loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 150                        # 2.5min.
    on-timeout = brightnessctl -s set 10         
    on-resume = brightnessctl -r         # monitor backlight restore.
}

listener { 
    timeout =  150
    on-timeout = brightnessctl -s -d asus::kbd_backlight set 0
    on-resume = brightnessctl -r -d asus::kbd_backlight
}

listener {
    timeout = 300                       # 5min
    on-timeout = loginctl lock-session  # lock screen when timeout has passed
}

listener {
    timeout = 330                                            # 5.5min
    on-timeout = hyprctl dispatch dpms off                   # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}