# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto

source = ~/.config/hypr/configs/environment.conf
source = ~/.config/hypr/configs/exec.conf
source = ~/.config/hypr/configs/keybindings.conf
source = ~/.config/hypr/configs/settings.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/rules.conf